/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.31
 * Generated at: 2022-02-26 01:50:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class MainLayout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/C:/KonaKart/webapps/konakart/WEB-INF/lib/struts2-core-kk-2.3.8.jar!/META-INF/struts-tags.tld", Long.valueOf(1355748546000L));
    _jspx_dependants.put("/WEB-INF/jsp/LiferayIncludes.jsp", Long.valueOf(1640259136000L));
    _jspx_dependants.put("/WEB-INF/kk.tld", Long.valueOf(1640259136000L));
    _jspx_dependants.put("/WEB-INF/jsp/Taglibs.jsp", Long.valueOf(1640259136000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-kk-2.3.8.jar", Long.valueOf(1640253186000L));
    _jspx_dependants.put("/WEB-INF/tiles-jsp.tld", Long.valueOf(1640259136000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005fuseAttribute_0026_005fname_005fignore_005fid_005fclassname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005furl_0026_005faction_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ftiles_005fuseAttribute_0026_005fname_005fignore_005fid_005fclassname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005furl_0026_005faction_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ftiles_005fuseAttribute_0026_005fname_005fignore_005fid_005fclassname_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005furl_0026_005faction_005fnobody.release();
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\"\r\n");
      out.write("\"http://www.w3.org/TR/html4/strict.dtd\">\r\n");
      out.write("\r\n");
 com.konakart.al.KKAppEng kkEng = (com.konakart.al.KKAppEng) session.getAttribute("konakartKey");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");
if (kkEng != null) {
      out.write("\r\n");
      out.write(" \t");
      //  tiles:useAttribute
      org.apache.tiles.jsp.taglib.UseAttributeTag _jspx_th_tiles_005fuseAttribute_005f0 = (org.apache.tiles.jsp.taglib.UseAttributeTag) _005fjspx_005ftagPool_005ftiles_005fuseAttribute_0026_005fname_005fignore_005fid_005fclassname_005fnobody.get(org.apache.tiles.jsp.taglib.UseAttributeTag.class);
      boolean _jspx_th_tiles_005fuseAttribute_005f0_reused = false;
      try {
        _jspx_th_tiles_005fuseAttribute_005f0.setPageContext(_jspx_page_context);
        _jspx_th_tiles_005fuseAttribute_005f0.setParent(null);
        // /WEB-INF/jsp/MainLayout.jsp(28,2) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_tiles_005fuseAttribute_005f0.setId("contentClass");
        // /WEB-INF/jsp/MainLayout.jsp(28,2) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_tiles_005fuseAttribute_005f0.setName("contentClass");
        // /WEB-INF/jsp/MainLayout.jsp(28,2) name = classname type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_tiles_005fuseAttribute_005f0.setClassname("java.lang.String");
        // /WEB-INF/jsp/MainLayout.jsp(28,2) name = ignore type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_tiles_005fuseAttribute_005f0.setIgnore(true);
        int _jspx_eval_tiles_005fuseAttribute_005f0 = _jspx_th_tiles_005fuseAttribute_005f0.doStartTag();
        if (_jspx_th_tiles_005fuseAttribute_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ftiles_005fuseAttribute_0026_005fname_005fignore_005fid_005fclassname_005fnobody.reuse(_jspx_th_tiles_005fuseAttribute_005f0);
        _jspx_th_tiles_005fuseAttribute_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tiles_005fuseAttribute_005f0, _jsp_getInstanceManager(), _jspx_th_tiles_005fuseAttribute_005f0_reused);
      }
      java.lang.String contentClass = null;
      contentClass = (java.lang.String) _jspx_page_context.findAttribute("contentClass");
      out.write("\r\n");
      out.write("    ");
kkEng.setContentClass(contentClass);
      out.write("\r\n");
      out.write("    ");
 if (kkEng.getProductMgr().getCurrentCategoriesLength() == 0 && contentClass.equalsIgnoreCase("narrow")){
      out.write("\r\n");
      out.write("    \t");
kkEng.setContentClass("wide");
      out.write("\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("    ");
 int menuType =  kkEng.getPropertyAsInt("menu.type", 1);
      out.write("\r\n");
      out.write("    ");
      //  tiles:useAttribute
      org.apache.tiles.jsp.taglib.UseAttributeTag _jspx_th_tiles_005fuseAttribute_005f1 = (org.apache.tiles.jsp.taglib.UseAttributeTag) _005fjspx_005ftagPool_005ftiles_005fuseAttribute_0026_005fname_005fignore_005fid_005fclassname_005fnobody.get(org.apache.tiles.jsp.taglib.UseAttributeTag.class);
      boolean _jspx_th_tiles_005fuseAttribute_005f1_reused = false;
      try {
        _jspx_th_tiles_005fuseAttribute_005f1.setPageContext(_jspx_page_context);
        _jspx_th_tiles_005fuseAttribute_005f1.setParent(null);
        // /WEB-INF/jsp/MainLayout.jsp(34,4) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_tiles_005fuseAttribute_005f1.setId("defName");
        // /WEB-INF/jsp/MainLayout.jsp(34,4) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_tiles_005fuseAttribute_005f1.setName("defName");
        // /WEB-INF/jsp/MainLayout.jsp(34,4) name = classname type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_tiles_005fuseAttribute_005f1.setClassname("java.lang.String");
        // /WEB-INF/jsp/MainLayout.jsp(34,4) name = ignore type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_tiles_005fuseAttribute_005f1.setIgnore(true);
        int _jspx_eval_tiles_005fuseAttribute_005f1 = _jspx_th_tiles_005fuseAttribute_005f1.doStartTag();
        if (_jspx_th_tiles_005fuseAttribute_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ftiles_005fuseAttribute_0026_005fname_005fignore_005fid_005fclassname_005fnobody.reuse(_jspx_th_tiles_005fuseAttribute_005f1);
        _jspx_th_tiles_005fuseAttribute_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tiles_005fuseAttribute_005f1, _jsp_getInstanceManager(), _jspx_th_tiles_005fuseAttribute_005f1_reused);
      }
      java.lang.String defName = null;
      defName = (java.lang.String) _jspx_page_context.findAttribute("defName");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");
if (kkEng.isPortlet()) {
      out.write("\r\n");
      out.write("    \t");
      out.write("\r\n");
      out.write("\t    ");
request.getSession().setAttribute("konakartKey", kkEng); 
      out.write(" \r\n");
      out.write("\t    ");
 boolean dontSetContext =  kkEng.getPropertyAsBoolean("dont.set.portlet.context.path", false);
      out.write("\r\n");
      out.write("\t    ");
if (!dontSetContext) {
      out.write("\r\n");
      out.write("\t\t    ");
kkEng.setPortletContextPath(request.getContextPath());
      out.write("\r\n");
      out.write("\t\t    <input id=\"kk_context\" type=\"hidden\" value=\"");
      out.print(request.getContextPath());
      out.write("\"/>\r\n");
      out.write("\t    ");
 } 
      out.write("\r\n");
      out.write("\t\t<input id=\"kk_portlet_id\" type=\"hidden\" value=\"");
      out.print(request.getAttribute("PORTLET_ID"));
      out.write("\"/>\r\n");
      out.write("\t\t<input id=\"kk_sample_url\" type=\"hidden\" value=\"");
      if (_jspx_meth_s_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"/>\t\r\n");
      out.write("\t\t<input type=\"hidden\" value=\"");
      out.print(kkEng.getXsrfToken());
      out.write("\" id=\"kk_xsrf_token\"/>\t\t\t\r\n");
      out.write("\t\t<div id=\"kk-portlet-body\">\t\t\r\n");
      out.write("    ");
 } else { 
      out.write("\r\n");
      out.write("\t\t<html>\r\n");
      out.write("\t\t\t<head>\r\n");
      out.write("\t\t\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t\t\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=1\" />\r\n");
      out.write("\t\t\t\t<title>");
      out.print(kkEng.getPageTitle());
      out.write("</title>\r\n");
      out.write("\t\t\t\t<meta name=\"keywords\" content=\"");
      out.print(kkEng.getMetaKeywords());
      out.write("\" />\r\n");
      out.write("\t\t\t\t<meta name=\"description\" content=\"");
      out.print(kkEng.getMetaDescription());
      out.write("\" />\r\n");
      out.write("\t\t\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("\t\t\t\t");
for (java.util.Iterator<String> iterator = kkEng.getMetaList().iterator(); iterator.hasNext();) {out.print(iterator.next());}
      out.write("\r\n");
      out.write("\t\t\t\t<link type=\"text/css\" rel=\"stylesheet\" href=\"https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css\" />\r\n");
      out.write("\t\t\t\t<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(kkEng.getStyleBase());
      out.write("/jquery.selectboxit.css\" />\r\n");
      out.write("\t\t\t\t<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(kkEng.getStyleBase());
      out.write("/font-awesome/css/font-awesome.css\" />\r\n");
      out.write("\t\t\t\t<link type='text/css' rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600,700'  >\t\t\r\n");
      out.write("\t\t\t\t<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(kkEng.getStyleBase());
      out.write("/jcarousel.css\" />\t\t\t\t\r\n");
      out.write("\t\t\t\t<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(kkEng.getStyleBase());
      out.write("/kk-style.css\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<script src=\"https://code.jquery.com/jquery-3.3.1.min.js\" integrity=\"sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=\" crossorigin=\"anonymous\"></script>\t\t\t\t\r\n");
      out.write("\t\t\t\t<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.min.js\" integrity=\"sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\" src=\"");
      out.print(kkEng.getScriptBase());
      out.write("/jquery.validate.min.js\"></script>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\" src=\"");
      out.print(kkEng.getScriptBase());
      out.write("/jquery.selectboxit.min.js\"></script>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\" src=\"");
      out.print(kkEng.getScriptBase());
      out.write("/jquery.ui.datepicker-en.js\"></script>\t\t\t \r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\" src=\"");
      out.print(kkEng.getScriptBase());
      out.write("/jquery.ui.datepicker-de.js\"></script>\t\t\t \r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\" src=\"");
      out.print(kkEng.getScriptBase());
      out.write("/jquery.ui.datepicker-pt.js\"></script>\t\t\t \r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\" src=\"");
      out.print(kkEng.getScriptBase());
      out.write("/jquery.ui.datepicker-es.js\"></script>\t\t\t \r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\" src=\"");
      out.print(kkEng.getScriptBase());
      out.write("/ddpowerzoomer.js\">\r\n");
      out.write("\t\t\t\t/***********************************************\r\n");
      out.write("\t\t\t\t* Image Power Zoomer- (c) Dynamic Drive DHTML code library (www.dynamicdrive.com)\r\n");
      out.write("\t\t\t\t* This notice MUST stay intact for legal use\r\n");
      out.write("\t\t\t\t* Visit Dynamic Drive at http://www.dynamicdrive.com/ for this script and 100s more\r\n");
      out.write("\t\t\t\t***********************************************/\r\n");
      out.write("\t\t\t\t</script>\t\t\t \r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\" src=\"");
      out.print(kkEng.getScriptBase());
      out.write("/jquery.jcarousel.min.js\"></script>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\" src=\"");
      out.print(kkEng.getScriptBase());
      out.write("/jquery.touchSwipe.min.js\"></script>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\" src=\"");
      out.print(kkEng.getScriptBase());
      out.write("/jquery.cookie.js\"></script>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\" src=\"");
      out.print(kkEng.getScriptBase());
      out.write("/jquery-backward-timer.min.js\"></script>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\" src=\"");
      out.print(kkEng.getScriptBase());
      out.write("/kk.js\"></script>\t\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\" src=\"");
      out.print(kkEng.getScriptBase());
      out.write("/kk.proddetails.js\"></script>\t\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\" src=\"");
      out.print(kkEng.getScriptBase());
      out.write("/kk.validation.js\"></script>\t\r\n");
      out.write("\t\t\t\t");
if (menuType == 2) {
      out.write("\r\n");
      out.write("\t\t\t\t\t<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(kkEng.getStyleBase());
      out.write("/smartmenus.css\" />\r\n");
      out.write("\t\t\t\t\t<script type=\"text/javascript\" src=\"");
      out.print(kkEng.getScriptBase());
      out.write("/smartmenus.js\"></script>\t\t\t\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t// Picture element HTML5 shiv\r\n");
      out.write("\t\t\t\tdocument.createElement( \"picture\" );\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\" src=\"");
      out.print(kkEng.getScriptBase());
      out.write("/picturefill-min.js\"></script>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t");

				// Set the base
				String scheme = pageContext.getRequest().getScheme()+"://";
				String server = pageContext.getRequest().getServerName();
				int port = pageContext.getRequest().getServerPort();
				String path = session.getServletContext().getContextPath();
				String base = scheme+server+((port==80)?"":":"+port)+path+"/";
				
      out.write("\r\n");
      out.write("\t\t\t\t<base href=\"");
      out.print(base);
      out.write("\"/>\r\n");
      out.write("\t\t\t\t<!-- The version below for obtaining the base is sometimes better on IIS.             -->\r\n");
      out.write("\t\t\t\t<!-- If you rely on the above for getting the base you get http://localhost so unless -->\r\n");
      out.write("\t\t\t\t<!-- IIS is configured to Rewrite the outbound URLs it fails.                         -->\r\n");
      out.write("\t\t\t\t<!-- base href=\"");
      out.print(kkEng.getConfig("KK_BASE_URL") );
      out.write("\"/ -->\r\n");
      out.write("\t\t\t\t<!--- KonaKart v9.4.0.2.");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SVN_REVISION}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" -->\r\n");
      out.write("\t\t\t</head>\r\n");
      out.write("\t\t\t");
if (defName != null) {
      out.write("\r\n");
      out.write("\t\t\t\t<body id=\"");
      out.print(defName);
      out.write("\">\r\n");
      out.write("\t\t\t");
} else {
      out.write("\r\n");
      out.write("\t\t\t\t<body>\r\n");
      out.write("\t\t\t");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
 boolean showMessengerPlugin =  kkEng.getConfigAsBoolean("MODULE_OTHER_MESSENGER_PLUGIN_STATUS", false, false, false);
      out.write("\r\n");
      out.write("\t\t\t");
if (showMessengerPlugin && !(defName != null && defName.equals("catalog.login.page"))) {
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t  window.fbAsyncInit = function() {\r\n");
      out.write("\t\t\t\t    FB.init({\r\n");
      out.write("\t\t\t\t      appId            : '");
      out.print(kkEng.getConfig("MODULE_OTHER_MESSENGER_PLUGIN_FACEBOOK_APP_ID") );
      out.write("',\r\n");
      out.write("\t\t\t\t      autoLogAppEvents : true,\r\n");
      out.write("\t\t\t\t      xfbml            : true,\r\n");
      out.write("\t\t\t\t      version          : 'v6.0'\r\n");
      out.write("\t\t\t\t    });\r\n");
      out.write("\t\t\t\t  };\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t  (function(d, s, id){\r\n");
      out.write("\t\t\t\t     var js, fjs = d.getElementsByTagName(s)[0];\r\n");
      out.write("\t\t\t\t     if (d.getElementById(id)) {return;}\r\n");
      out.write("\t\t\t\t     js = d.createElement(s); js.id = id;\r\n");
      out.write("\t\t\t\t     js.src = \"https://connect.facebook.net/en_US/sdk/xfbml.customerchat.js\";\r\n");
      out.write("\t\t\t\t     fjs.parentNode.insertBefore(js, fjs);\r\n");
      out.write("\t\t\t\t   }(document, 'script', 'facebook-jssdk'));\r\n");
      out.write("\t\t\t\t</script>\t\r\n");
      out.write("\t\t\t\t<div class=\"fb-customerchat\"\r\n");
      out.write(" \t\t\t\t\tpage_id=\"");
      out.print(kkEng.getConfig("MODULE_OTHER_MESSENGER_PLUGIN_FACEBOOK_PAGE_ID") );
      out.write("\"\r\n");
      out.write(" \t\t\t\t\tminimized=\"");
      out.print(kkEng.getConfig("MODULE_OTHER_MESSENGER_PLUGIN_MINIMIZED") );
      out.write("\">\r\n");
      out.write("\t\t\t\t</div>\t\t\t\r\n");
      out.write("\t\t\t");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<input type=\"hidden\" value=\"");
      out.print(kkEng.getXsrfToken());
      out.write("\" id=\"kk_xsrf_token\"/>\r\n");
      out.write("\t");
}
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.print(kkEng.getAnalyticsCode());
      out.write("\r\n");
      out.write("\t<script language=\"JavaScript\" type=\"text/javascript\">\r\n");
      out.write("\t\tif (top.location != location) {\r\n");
      out.write("\t\t\t\t\ttop.location.href = document.location.href ;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t// Set jquery validation messages\r\n");
      out.write("\t\t\tjQuery.validator.messages = {\r\n");
      out.write("\t\t\t\t\tstate: '");
      out.print(kkEng.getMsg("jquery.validator.required"));
      out.write("',\r\n");
      out.write("\t\t\t\t\tcountry: '");
      out.print(kkEng.getMsg("jquery.validator.required"));
      out.write("',\r\n");
      out.write("\t\t\t\t\trequired: '");
      out.print(kkEng.getMsg("jquery.validator.required"));
      out.write("',\r\n");
      out.write("\t\t\t\t\tcreditcard: '");
      out.print(kkEng.getMsg("jquery.validator.creditcard"));
      out.write("',\r\n");
      out.write("\t\t\t\t\tdigits: '");
      out.print(kkEng.getMsg("jquery.validator.digits"));
      out.write("',\r\n");
      out.write("\t\t\t\t\tmaxlength: jQuery.validator.format('");
      out.print(kkEng.getMsg("jquery.validator.maxlength"));
      out.write(" {0} ");
      out.print(kkEng.getMsg("jquery.validator.maxlength1"));
      out.write("'),\r\n");
      out.write("\t\t\t\t\tminlength: jQuery.validator.format('");
      out.print(kkEng.getMsg("jquery.validator.minlength"));
      out.write(" {0} ");
      out.print(kkEng.getMsg("jquery.validator.minlength1"));
      out.write("'),\r\n");
      out.write("\t\t\t\t\texpirydate: '");
      out.print(kkEng.getMsg("jquery.validator.expiryMMYY"));
      out.write("',\r\n");
      out.write("\t\t\t\t\temail:\t'");
      out.print(kkEng.getMsg("jquery.validator.email"));
      out.write("',\r\n");
      out.write("\t\t\t\t\turl:\t'");
      out.print(kkEng.getMsg("jquery.validator.url"));
      out.write("',\r\n");
      out.write("\t\t\t\t\tnumber:\t'");
      out.print(kkEng.getMsg("jquery.validator.number"));
      out.write("',\r\n");
      out.write(" \t\t\t\t\tequalTo: '");
      out.print(kkEng.getMsg("jquery.validator.equalTo"));
      out.write("',\r\n");
      out.write(" \t\t\t\t\tphone_regex: '");
      out.print(kkEng.getMsg("jquery.validator.phone"));
      out.write("'\r\n");
      out.write("\t\t};\t\t \r\n");
      out.write("\t</script>\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t    \t\t<div id=\"page-container\">\r\n");
      out.write("\t    \t\t\t<div id=\"page\" class=\"");
      if (_jspx_meth_tiles_005finsertAttribute_005f2(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div id=\"content\" class=\"");
      out.print(kkEng.getContentClass());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f6(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("\t\t\t\t\t \t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f7(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f8(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f9(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f10(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f11(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f12(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t    \t\t</div>\r\n");
      out.write("\t    \t\t</div>\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f13(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("    ");
if (!kkEng.isPortlet()) {
      out.write("\r\n");
      out.write("\t\t\t</body>\r\n");
      out.write("\t\t</html>\r\n");
      out.write("\t");
} else {
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t");
}
      out.write('\r');
      out.write('\n');
}
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:url
    org.apache.struts2.views.jsp.URLTag _jspx_th_s_005furl_005f0 = (org.apache.struts2.views.jsp.URLTag) _005fjspx_005ftagPool_005fs_005furl_0026_005faction_005fnobody.get(org.apache.struts2.views.jsp.URLTag.class);
    boolean _jspx_th_s_005furl_005f0_reused = false;
    try {
      _jspx_th_s_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005furl_005f0.setParent(null);
      // /WEB-INF/jsp/MainLayout.jsp(45,49) name = action type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005furl_005f0.setAction("KK_ACTION");
      int _jspx_eval_s_005furl_005f0 = _jspx_th_s_005furl_005f0.doStartTag();
      if (_jspx_th_s_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005furl_0026_005faction_005fnobody.reuse(_jspx_th_s_005furl_005f0);
      _jspx_th_s_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_s_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f0 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    boolean _jspx_th_tiles_005finsertAttribute_005f0_reused = false;
    try {
      _jspx_th_tiles_005finsertAttribute_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tiles_005finsertAttribute_005f0.setParent(null);
      // /WEB-INF/jsp/MainLayout.jsp(170,4) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsertAttribute_005f0.setName("header1");
      int _jspx_eval_tiles_005finsertAttribute_005f0 = _jspx_th_tiles_005finsertAttribute_005f0.doStartTag();
      if (_jspx_th_tiles_005finsertAttribute_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f0);
      _jspx_th_tiles_005finsertAttribute_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tiles_005finsertAttribute_005f0, _jsp_getInstanceManager(), _jspx_th_tiles_005finsertAttribute_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f1 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    boolean _jspx_th_tiles_005finsertAttribute_005f1_reused = false;
    try {
      _jspx_th_tiles_005finsertAttribute_005f1.setPageContext(_jspx_page_context);
      _jspx_th_tiles_005finsertAttribute_005f1.setParent(null);
      // /WEB-INF/jsp/MainLayout.jsp(171,4) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsertAttribute_005f1.setName("header2");
      int _jspx_eval_tiles_005finsertAttribute_005f1 = _jspx_th_tiles_005finsertAttribute_005f1.doStartTag();
      if (_jspx_th_tiles_005finsertAttribute_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f1);
      _jspx_th_tiles_005finsertAttribute_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tiles_005finsertAttribute_005f1, _jsp_getInstanceManager(), _jspx_th_tiles_005finsertAttribute_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f2 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    boolean _jspx_th_tiles_005finsertAttribute_005f2_reused = false;
    try {
      _jspx_th_tiles_005finsertAttribute_005f2.setPageContext(_jspx_page_context);
      _jspx_th_tiles_005finsertAttribute_005f2.setParent(null);
      // /WEB-INF/jsp/MainLayout.jsp(173,30) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsertAttribute_005f2.setName("pageClass");
      int _jspx_eval_tiles_005finsertAttribute_005f2 = _jspx_th_tiles_005finsertAttribute_005f2.doStartTag();
      if (_jspx_th_tiles_005finsertAttribute_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f2);
      _jspx_th_tiles_005finsertAttribute_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tiles_005finsertAttribute_005f2, _jsp_getInstanceManager(), _jspx_th_tiles_005finsertAttribute_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f3 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    boolean _jspx_th_tiles_005finsertAttribute_005f3_reused = false;
    try {
      _jspx_th_tiles_005finsertAttribute_005f3.setPageContext(_jspx_page_context);
      _jspx_th_tiles_005finsertAttribute_005f3.setParent(null);
      // /WEB-INF/jsp/MainLayout.jsp(174,6) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsertAttribute_005f3.setName("header3");
      int _jspx_eval_tiles_005finsertAttribute_005f3 = _jspx_th_tiles_005finsertAttribute_005f3.doStartTag();
      if (_jspx_th_tiles_005finsertAttribute_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f3);
      _jspx_th_tiles_005finsertAttribute_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tiles_005finsertAttribute_005f3, _jsp_getInstanceManager(), _jspx_th_tiles_005finsertAttribute_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f4 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    boolean _jspx_th_tiles_005finsertAttribute_005f4_reused = false;
    try {
      _jspx_th_tiles_005finsertAttribute_005f4.setPageContext(_jspx_page_context);
      _jspx_th_tiles_005finsertAttribute_005f4.setParent(null);
      // /WEB-INF/jsp/MainLayout.jsp(175,6) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsertAttribute_005f4.setName("header4");
      int _jspx_eval_tiles_005finsertAttribute_005f4 = _jspx_th_tiles_005finsertAttribute_005f4.doStartTag();
      if (_jspx_th_tiles_005finsertAttribute_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f4);
      _jspx_th_tiles_005finsertAttribute_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tiles_005finsertAttribute_005f4, _jsp_getInstanceManager(), _jspx_th_tiles_005finsertAttribute_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f5 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    boolean _jspx_th_tiles_005finsertAttribute_005f5_reused = false;
    try {
      _jspx_th_tiles_005finsertAttribute_005f5.setPageContext(_jspx_page_context);
      _jspx_th_tiles_005finsertAttribute_005f5.setParent(null);
      // /WEB-INF/jsp/MainLayout.jsp(176,6) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsertAttribute_005f5.setName("left1");
      int _jspx_eval_tiles_005finsertAttribute_005f5 = _jspx_th_tiles_005finsertAttribute_005f5.doStartTag();
      if (_jspx_th_tiles_005finsertAttribute_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f5);
      _jspx_th_tiles_005finsertAttribute_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tiles_005finsertAttribute_005f5, _jsp_getInstanceManager(), _jspx_th_tiles_005finsertAttribute_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f6 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    boolean _jspx_th_tiles_005finsertAttribute_005f6_reused = false;
    try {
      _jspx_th_tiles_005finsertAttribute_005f6.setPageContext(_jspx_page_context);
      _jspx_th_tiles_005finsertAttribute_005f6.setParent(null);
      // /WEB-INF/jsp/MainLayout.jsp(178,7) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsertAttribute_005f6.setName("body1");
      int _jspx_eval_tiles_005finsertAttribute_005f6 = _jspx_th_tiles_005finsertAttribute_005f6.doStartTag();
      if (_jspx_th_tiles_005finsertAttribute_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f6);
      _jspx_th_tiles_005finsertAttribute_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tiles_005finsertAttribute_005f6, _jsp_getInstanceManager(), _jspx_th_tiles_005finsertAttribute_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f7 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    boolean _jspx_th_tiles_005finsertAttribute_005f7_reused = false;
    try {
      _jspx_th_tiles_005finsertAttribute_005f7.setPageContext(_jspx_page_context);
      _jspx_th_tiles_005finsertAttribute_005f7.setParent(null);
      // /WEB-INF/jsp/MainLayout.jsp(179,8) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsertAttribute_005f7.setName("body2");
      int _jspx_eval_tiles_005finsertAttribute_005f7 = _jspx_th_tiles_005finsertAttribute_005f7.doStartTag();
      if (_jspx_th_tiles_005finsertAttribute_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f7);
      _jspx_th_tiles_005finsertAttribute_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tiles_005finsertAttribute_005f7, _jsp_getInstanceManager(), _jspx_th_tiles_005finsertAttribute_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f8 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    boolean _jspx_th_tiles_005finsertAttribute_005f8_reused = false;
    try {
      _jspx_th_tiles_005finsertAttribute_005f8.setPageContext(_jspx_page_context);
      _jspx_th_tiles_005finsertAttribute_005f8.setParent(null);
      // /WEB-INF/jsp/MainLayout.jsp(180,7) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsertAttribute_005f8.setName("body3");
      int _jspx_eval_tiles_005finsertAttribute_005f8 = _jspx_th_tiles_005finsertAttribute_005f8.doStartTag();
      if (_jspx_th_tiles_005finsertAttribute_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f8);
      _jspx_th_tiles_005finsertAttribute_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tiles_005finsertAttribute_005f8, _jsp_getInstanceManager(), _jspx_th_tiles_005finsertAttribute_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f9 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    boolean _jspx_th_tiles_005finsertAttribute_005f9_reused = false;
    try {
      _jspx_th_tiles_005finsertAttribute_005f9.setPageContext(_jspx_page_context);
      _jspx_th_tiles_005finsertAttribute_005f9.setParent(null);
      // /WEB-INF/jsp/MainLayout.jsp(181,7) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsertAttribute_005f9.setName("body4");
      int _jspx_eval_tiles_005finsertAttribute_005f9 = _jspx_th_tiles_005finsertAttribute_005f9.doStartTag();
      if (_jspx_th_tiles_005finsertAttribute_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f9);
      _jspx_th_tiles_005finsertAttribute_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tiles_005finsertAttribute_005f9, _jsp_getInstanceManager(), _jspx_th_tiles_005finsertAttribute_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f10 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    boolean _jspx_th_tiles_005finsertAttribute_005f10_reused = false;
    try {
      _jspx_th_tiles_005finsertAttribute_005f10.setPageContext(_jspx_page_context);
      _jspx_th_tiles_005finsertAttribute_005f10.setParent(null);
      // /WEB-INF/jsp/MainLayout.jsp(182,7) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsertAttribute_005f10.setName("body5");
      int _jspx_eval_tiles_005finsertAttribute_005f10 = _jspx_th_tiles_005finsertAttribute_005f10.doStartTag();
      if (_jspx_th_tiles_005finsertAttribute_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f10);
      _jspx_th_tiles_005finsertAttribute_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tiles_005finsertAttribute_005f10, _jsp_getInstanceManager(), _jspx_th_tiles_005finsertAttribute_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f11 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    boolean _jspx_th_tiles_005finsertAttribute_005f11_reused = false;
    try {
      _jspx_th_tiles_005finsertAttribute_005f11.setPageContext(_jspx_page_context);
      _jspx_th_tiles_005finsertAttribute_005f11.setParent(null);
      // /WEB-INF/jsp/MainLayout.jsp(183,7) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsertAttribute_005f11.setName("body6");
      int _jspx_eval_tiles_005finsertAttribute_005f11 = _jspx_th_tiles_005finsertAttribute_005f11.doStartTag();
      if (_jspx_th_tiles_005finsertAttribute_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f11);
      _jspx_th_tiles_005finsertAttribute_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tiles_005finsertAttribute_005f11, _jsp_getInstanceManager(), _jspx_th_tiles_005finsertAttribute_005f11_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f12 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    boolean _jspx_th_tiles_005finsertAttribute_005f12_reused = false;
    try {
      _jspx_th_tiles_005finsertAttribute_005f12.setPageContext(_jspx_page_context);
      _jspx_th_tiles_005finsertAttribute_005f12.setParent(null);
      // /WEB-INF/jsp/MainLayout.jsp(185,6) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsertAttribute_005f12.setName("footer1");
      int _jspx_eval_tiles_005finsertAttribute_005f12 = _jspx_th_tiles_005finsertAttribute_005f12.doStartTag();
      if (_jspx_th_tiles_005finsertAttribute_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f12);
      _jspx_th_tiles_005finsertAttribute_005f12_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tiles_005finsertAttribute_005f12, _jsp_getInstanceManager(), _jspx_th_tiles_005finsertAttribute_005f12_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f13(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f13 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    boolean _jspx_th_tiles_005finsertAttribute_005f13_reused = false;
    try {
      _jspx_th_tiles_005finsertAttribute_005f13.setPageContext(_jspx_page_context);
      _jspx_th_tiles_005finsertAttribute_005f13.setParent(null);
      // /WEB-INF/jsp/MainLayout.jsp(188,4) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsertAttribute_005f13.setName("footer2");
      int _jspx_eval_tiles_005finsertAttribute_005f13 = _jspx_th_tiles_005finsertAttribute_005f13.doStartTag();
      if (_jspx_th_tiles_005finsertAttribute_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f13);
      _jspx_th_tiles_005finsertAttribute_005f13_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tiles_005finsertAttribute_005f13, _jsp_getInstanceManager(), _jspx_th_tiles_005finsertAttribute_005f13_reused);
    }
    return false;
  }
}
