package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetAllProductRelationships - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetAllProductRelationships
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetAllProductRelationships(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public ProductRelationshipIf[] getAllProductRelationships() throws KKException
     {
         return kkEng.getAllProductRelationships();
     }
}
