package com.konakart.app;

import com.konakart.appif.*;

/**
 *  The KonaKart Custom Engine - GetMiscItemsPerType - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class GetMiscItemsPerType
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public GetMiscItemsPerType(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public MiscItemIf[] getMiscItemsPerType(int typeId, int languageId) throws KKException
     {
         return kkEng.getMiscItemsPerType(typeId, languageId);
     }
}
