package com.konakart.app;

/**
 *  The KonaKart Custom Engine - IsCustomerSubscribedToNewsletter - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class IsCustomerSubscribedToNewsletter
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public IsCustomerSubscribedToNewsletter(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public boolean isCustomerSubscribedToNewsletter(String emailAddr) throws KKException
     {
         return kkEng.isCustomerSubscribedToNewsletter(emailAddr);
     }
}
