package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteCatalogWithOptions - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteCatalogWithOptions
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteCatalogWithOptions(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void deleteCatalogWithOptions(String sessionId, int catalogId, AdminDeleteCatalogOptions options) throws KKAdminException
     {
         kkAdminEng.deleteCatalogWithOptions(sessionId, catalogId, options);
     }
}
