package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteOrderReturnStatus - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteOrderReturnStatus
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteOrderReturnStatus(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int deleteOrderReturnStatus(String sessionId, int id) throws KKAdminException
     {
         return kkAdminEng.deleteOrderReturnStatus(sessionId, id);
     }
}
