package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - DeleteReviewsPerCustomer - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class DeleteReviewsPerCustomer
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public DeleteReviewsPerCustomer(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void deleteReviewsPerCustomer(String sessionId, int customerId) throws KKAdminException
     {
         kkAdminEng.deleteReviewsPerCustomer(sessionId, customerId);
     }
}
