package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetAllOrderReturnStatuses - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetAllOrderReturnStatuses
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetAllOrderReturnStatuses(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminOrderReturnStatus[] getAllOrderReturnStatuses(int languageId) throws KKAdminException
     {
         return kkAdminEng.getAllOrderReturnStatuses(languageId);
     }
}
