package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetOrderReturnStatuses - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetOrderReturnStatuses
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetOrderReturnStatuses(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminOrderReturnStatusSearchResult getOrderReturnStatuses( AdminOrderReturnStatusSearch search) throws KKAdminException
     {
         return kkAdminEng.getOrderReturnStatuses(search);
     }
}
