package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakart.app.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - GetSuggestions - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class GetSuggestions
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public GetSuggestions(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public AdminSuggestionSearchResult getSuggestions(String sessionId, AdminSuggestion suggestion, AdminDataDescriptor dataDesc) throws KKAdminException
     {
         return kkAdminEng.getSuggestions(sessionId, suggestion, dataDesc);
     }
}
