package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertSuggestions - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertSuggestions
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertSuggestions(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void insertSuggestions(String sessionId, AdminSuggestion[] suggestions) throws KKAdminException
     {
         kkAdminEng.insertSuggestions(sessionId, suggestions);
     }
}
