package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - InsertOrderReturnStatuses - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class InsertOrderReturnStatuses
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public InsertOrderReturnStatuses(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int insertOrderReturnStatuses(String sessionId, AdminOrderReturnStatus[] statuses) throws KKAdminException
     {
         return kkAdminEng.insertOrderReturnStatuses(sessionId, statuses);
     }
}
