package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - RemoveMallStore - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class RemoveMallStore
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public RemoveMallStore(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void removeMallStore(String sessionId, String storeId) throws KKAdminException
     {
         kkAdminEng.removeMallStore(sessionId, storeId);
     }
}
