package com.konakartadmin.app;

import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - RemoveRelatedProduct - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class RemoveRelatedProduct
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public RemoveRelatedProduct(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public void removeRelatedProduct(String sessionId, int productIdFrom, int productIdTo, int relationType) throws KKAdminException
     {
         kkAdminEng.removeRelatedProduct(sessionId, productIdFrom, productIdTo, relationType);
     }
}
