package com.konakartadmin.app;

import com.konakartadmin.appif.*;
import com.konakartadmin.bl.KKAdmin;

/**
 *  The KonaKart Custom Engine - UpdateOrderReturnStatus - Generated by CreateKKAdminCustomEng
 */
@SuppressWarnings("all")
public class UpdateOrderReturnStatus
{
    KKAdmin kkAdminEng = null;

    /**
     * Constructor
     */
     public UpdateOrderReturnStatus(KKAdmin _kkAdminEng)
     {
         kkAdminEng = _kkAdminEng;
     }

     public int updateOrderReturnStatus(String sessionId, AdminOrderReturnStatus status) throws KKAdminException
     {
         return kkAdminEng.updateOrderReturnStatus(sessionId, status);
     }
}
